[theme]
primaryColor = "#F21736"
backgroundColor = "orange"
[client]
showSidebarNavigation = false
[client]
showSidebarNavigation = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"